name: Publish

concurrency:
  group: publish

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.100

    - name: Get Engine Tag
      run: |
        cd RobustToolbox
        git fetch --depth=1

    - name: Package client
      run: |
        Tools/package_server_build.py -p win-x64 linux-x64 osx-x64 linux-arm64
        Tools/package_client_build.py

    - name: Update Build Info
      run: Tools/gen_build_info.py

    - name: Shuffle files around
      run: |
        mkdir "release/${{ github.sha }}"
        mv release/*.zip "release/${{ github.sha }}"

    - name: Upload files to centcomm
      uses: appleboy/scp-action@master
      with:
        host: hellomouse.net
        username: or14-builds
        key: ${{ secrets.OUTER_RIM_BUILDS_PUSH_KEY }}
        source: "release/${{ github.sha }}"
        target: "/home/or14-builds/public_html/builds/"
        strip_components: 1

    # For some fucking reason this doesn't work with hellomouse.net. FUCK. Poke moony to update shit.
    - name: Update manifest JSON
      uses: appleboy/ssh-action@master
      continue-on-error: true
      with:
        host: hellomouse.net
        username: or14-builds
        key: ${{ secrets.OUTER_RIM_BUILDS_PUSH_KEY }}
        script: /home/or14-builds/push.ps1 ${{ github.sha }}
